# Generated by Django 4.2.5 on 2023-09-23 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_loc', models.FloatField(blank=True, null=True)),
                ('prix_achat', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('box', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Boutique',
                'db_table': 'boutique',
            },
        ),
        migrations.CreateModel(
            name='Categorize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorize', models.CharField(choices=[('1', 'En vente'), ('2', 'En location'), ('3', 'Les deux')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Chambre',
                'db_table': 'chambre',
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('way', models.CharField(blank=True, max_length=255, null=True)),
                ('prix_loc', models.FloatField(blank=True, null=True)),
                ('prix_achat', models.FloatField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='post.category')),
            ],
            options={
                'verbose_name_plural': 'Maison',
                'db_table': 'maison',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default=None, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.CharField(default=None, max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('categorize', models.ManyToManyField(to='post.categorize')),
                ('id_BO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.boutique')),
                ('id_MA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.maison')),
            ],
            options={
                'verbose_name_plural': 'Poster',
                'db_table': 'poster',
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_loc', models.FloatField(blank=True, null=True)),
                ('prix_achat', models.FloatField(blank=True, null=True)),
                ('superficie', models.CharField(max_length=255)),
                ('chambre', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Terrain',
                'db_table': 'terrain',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.client')),
                ('marchandise_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.poster')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.prestateur')),
            ],
        ),
        migrations.AddField(
            model_name='poster',
            name='id_TE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.terrain'),
        ),
        migrations.AddField(
            model_name='poster',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.prestateur'),
        ),
        migrations.CreateModel(
            name='Louer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.client')),
                ('marchandise_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.poster')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.prestateur')),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('id_Bo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.boutique')),
                ('id_Ma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.maison')),
                ('id_Te', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.terrain')),
            ],
            options={
                'verbose_name_plural': 'Emplacement',
                'db_table': 'emplacement',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id_Po', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.poster')),
                ('id_Us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Commentaire',
                'db_table': 'commentaire',
            },
        ),
        migrations.CreateModel(
            name='Caracteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('climatiser', models.BooleanField(default=False)),
                ('ventiller', models.BooleanField(default=False)),
                ('carreau', models.BooleanField(default=False)),
                ('superficie', models.CharField(max_length=255)),
                ('id_CH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.chambre')),
                ('id_Ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.maison')),
            ],
            options={
                'verbose_name_plural': 'Caracteristics',
                'db_table': 'caracteristics',
            },
        ),
        migrations.AddField(
            model_name='boutique',
            name='category',
            field=models.ManyToManyField(to='post.category'),
        ),
    ]
